OrdererOrgs:
  - Name: Orderer
    Domain: supplychain.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4
      - Hostname: orderer5

PeerOrgs:
  - Name: FarmInspector
    Domain: farminspector.supplychain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Harvester
    Domain: harvester.supplychain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Exporter
    Domain: exporter.supplychain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Importer
    Domain: importer.supplychain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
      
  - Name: Processor
    Domain: processor.supplychain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
